vkTOKEN='HERE IS YOURS VK TOKEN (a standalone app token with wall,offline permissions)'




#HERE YOU HAVE TO PASTE YOUR VK GROUP ID
MAINID=1234567





#HERE YOU HAVE TO PASTE YOUR VK ID (ONLY THIS USER CAN MANAGE THE GROUP)
ADMINID=1234567
